name: Muhrs - Quality consulting services
favicon: null
layout_spectrum: 0.3496840342413634
typography_spectrum: 0.6070240535773337
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.4844758310355246
  lightness: 0.09895317512564361
  saturation: 0.9852147740311921
  rhythmicContrast: 0.4398408003617078
purpose: []
